chore: re-add allow-direct-references
dont know how but i read it ass `index-strategy = "unsafe-best-match"` and removed it

`allow-direct-references` necessary to allow the direct referencing we are using wth for the torch dependencies with out it hatchling returns the below error

Call to `hatchling.build.build_editable` failed (exit status: 1)
...
line 1205, in dependencies_complex
          raise ValueError(message)
      ValueError: Dependency #106 of field `project.dependencies`
      cannot be a direct reference unless field
      `tool.hatch.metadata.allow-direct-references` is set to `true`

      hint: This usually indicates a problem with the package or the build
      environment.
Error: Process completed with exit code 1.